### ISSUE TITLE
OutOfRangeError (see above for traceback): PaddingFIFOQueue '_1_batch/padding_fifo_queue' is closed and has insufficient elements (requested 32, current size 0)

### ISSUE THREAD

**Issue by oguzzkck** [llSourcell/Neural_Network_Voices#9]
Traceback (most recent call last):                                    
  File "/Users/oguzkocak/.vscode/extensions/ms-python.python-2019.4.12954/pythonFiles/ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "/Users/oguzkocak/.vscode/extensions/ms-python.python-2019.4.12954/pythonFiles/lib/python/ptvsd/__main__.py", line 410, in main
    run()
  File "/Users/oguzkocak/.vscode/extensions/ms-python.python-2019.4.12954/pythonFiles/lib/python/ptvsd/__main__.py", line 291, in run_file
    runpy.run_path(target, run_name='__main__')
  File "/anaconda3/envs/YapayZeka/lib/python2.7/runpy.py", line 252, in run_path
    return _run_module_code(code, init_globals, run_name, path_name)
  File "/anaconda3/envs/YapayZeka/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/anaconda3/envs/YapayZeka/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/oguzkocak/Desktop/YapayZeka/Neural_Network_Voices-master/train1.py", line 96, in <module>
    train(logdir=logdir)
  File "/Users/oguzkocak/Desktop/YapayZeka/Neural_Network_Voices-master/train1.py", line 59, in train
    sess.run(train_op)
  File "/anaconda3/envs/YapayZeka/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/anaconda3/envs/YapayZeka/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/anaconda3/envs/YapayZeka/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/anaconda3/envs/YapayZeka/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: PaddingFIFOQueue '_1_batch/padding_fifo_queue' is closed and has insufficient elements (requested 32, current size 0)
         [[node batch (defined at /Users/oguzkocak/Desktop/YapayZeka/Neural_Network_Voices-master/data_load.py:224) ]]

Caused by op u'batch', defined at:
  File "/Users/oguzkocak/.vscode/extensions/ms-python.python-2019.4.12954/pythonFiles/ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "/Users/oguzkocak/.vscode/extensions/ms-python.python-2019.4.12954/pythonFiles/lib/python/ptvsd/__main__.py", line 410, in main
    run()
  File "/Users/oguzkocak/.vscode/extensions/ms-python.python-2019.4.12954/pythonFiles/lib/python/ptvsd/__main__.py", line 291, in run_file
    runpy.run_path(target, run_name='__main__')
  File "/anaconda3/envs/YapayZeka/lib/python2.7/runpy.py", line 252, in run_path
    return _run_module_code(code, init_globals, run_name, path_name)
  File "/anaconda3/envs/YapayZeka/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/anaconda3/envs/YapayZeka/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/oguzkocak/Desktop/YapayZeka/Neural_Network_Voices-master/train1.py", line 96, in <module>
    train(logdir=logdir)
  File "/Users/oguzkocak/Desktop/YapayZeka/Neural_Network_Voices-master/train1.py", line 17, in train
    model = Model(mode="train1", batch_size=hp.Train1.batch_size, queue=queue)
  File "/Users/oguzkocak/Desktop/YapayZeka/Neural_Network_Voices-master/models.py", line 22, in __init__
    self.x_mfcc, self.y_ppgs, self.y_spec, self.y_mel, self.num_batch = self.get_input(mode, batch_size, queue)
  File "/Users/oguzkocak/Desktop/YapayZeka/Neural_Network_Voices-master/models.py", line 51, in get_input
    x_mfcc, y_ppgs, num_batch = get_batch_queue(mode=mode, batch_size=batch_size)
  File "/Users/oguzkocak/Desktop/YapayZeka/Neural_Network_Voices-master/data_load.py", line 224, in get_batch_queue
    dynamic_pad=True)
  File "/anaconda3/envs/YapayZeka/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/anaconda3/envs/YapayZeka/lib/python2.7/site-packages/tensorflow/python/training/input.py", line 1019, in batch
    name=name)
  File "/anaconda3/envs/YapayZeka/lib/python2.7/site-packages/tensorflow/python/training/input.py", line 789, in _batch
    dequeued = queue.dequeue_many(batch_size, name=name)
  File "/anaconda3/envs/YapayZeka/lib/python2.7/site-packages/tensorflow/python/ops/data_flow_ops.py", line 488, in dequeue_many
    self._queue_ref, n=n, component_types=self._dtypes, name=name)
  File "/anaconda3/envs/YapayZeka/lib/python2.7/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 3645, in queue_dequeue_many_v2
    timeout_ms=timeout_ms, name=name)
  File "/anaconda3/envs/YapayZeka/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/anaconda3/envs/YapayZeka/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/anaconda3/envs/YapayZeka/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/anaconda3/envs/YapayZeka/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

OutOfRangeError (see above for traceback): PaddingFIFOQueue '_1_batch/padding_fifo_queue' is closed and has insufficient elements (requested 32, current size 0)
         [[node batch (defined at /Users/oguzkocak/Desktop/YapayZeka/Neural_Network_Voices-master/data_load.py:224) ]]

Terminated: 15

Do you have any idea about this problem ?

**Comment by mattpeng3** [comment]
Did you solve this? @llSourcell  did you encounter this too and any suggestions?
